export const SPECIALTIES = [
  "Allergy & Immunology",
  "Anaesthesiology",
  "Cardiology",
  "Cardiothoracic Surgery",
  "Dermatology",
  "Emergency Medicine",
  "Endocrinology",
  "Gastroenterology",
  "General Medicine",
  "General Surgery",
  "Geriatric Medicine",
  "Gynaecology",
  "Haematology",
  "Infectious Diseases",
  "Nephrology",
  "Neurology",
  "Neurosurgery",
  "Obstetrics",
  "Oncology",
  "Ophthalmology",
  "Orthopaedics",
  "Otolaryngology (ENT)",
  "Paediatrics",
  "Pain Medicine",
  "Palliative Care",
  "Plastic Surgery",
  "Psychiatry",
  "Radiology",
  "Rehabilitation Medicine",
  "Respiratory Medicine",
  "Rheumatology",
  "Urology",
  "Vascular Surgery",
] as const;

export type Specialty = (typeof SPECIALTIES)[number];
